import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className="font-inter flex flex-col h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="flex flex-1 relative w-full h-full">
        <Image className="brightness-[0.25]" layout="fill" src="/movies-bg.webp" alt="movies" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-10">
          <h1 className="font-extrabold text-gray-200 text-center text-7xl !leading-normal"> Welcome to Movies Rating app</h1>
        </div>
      </main>


    </div>
  )
}
